### PR TITLE
JOSS review

### PR DESCRIPTION
**Pull request by nevrome**
collecting the reactions to  [the JOSS review](https://github.com/openjournals/joss-reviews/issues/3092)

### CODE REVIEW

**Comment by nevrome** [comment]
Again thank you for your review, @corybrunson and @fabian-s. I think I addressed all the issues you raised - the respective commits should be linked in the issues. Maybe you could go through them once more. If you consider them to be solved you could close them directly.

 @stschiff Would you like to add anything to these changes and do you agree with the additional paragraph in the paper.md file?

**Comment by fabian-s** [comment]
other than that little <FILL IN THE BLANK> thing above, this looks ready to me.

**Comment by nevrome** [comment]
Good spotting, @fabian-s! I added my contact information.

**Comment by corybrunson** [comment]
@nevrome i made one suggestion in my remaining open issue.

Additionally, based on an exchange at the review, could you add a sentence or two statement of need to the documentation, e.g. the README or the package documentation page? These could be a simple shortening of the two paragraphs in the paper.

**Comment by nevrome** [comment]
@corybrunson 512f68a and f629656 replace the introduction both in the README and in `?bleiglas` with something a bit more substantial. I hope that covers what you meant :+1:

**Comment by corybrunson** [comment]
It suffices for me! Thanks @nevrome.

**Pull request merged**
